openapi: 3.0.1
info:
  title: Get Apps API
  version: "1.0"
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://8feea1f7d131.ngrok-free.app

security:
  - ApiKeyAuth: []

paths:
  /api/v1/app-service/get-apps:
    put:
      summary: List all apps.
      description: Get apps page. Given page number and page size. Supporting 25 / 50 page size.
      operationId: app_service_get_apps
      tags:
        - app-service
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1GetAppsRequest'
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1GetAppsResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/googlerpcStatus'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/googlerpcStatus'

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization

  schemas:
    v1GetAppsRequest:
      type: object
      properties:
        appName:
          type: string
          description: Filter by application name
        category:
          type: string
          description: Filter by category
        pageNumber:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32

    v1GetAppsResponse:
      type: object
      properties:
        appRows:
          type: array
          items:
            $ref: '#/components/schemas/v1AppRow'
        totalCount:
          type: integer
          format: int32
      example:
        appRows:
          - appId: "appId"
            appName: "appName"
            appSources: ["source1", "source2"]
            category: "category"
        totalCount: 2

    v1AppRow:
      type: object
      properties:
        appId:
          type: string
        appName:
          type: string
        appSources:
          type: array
          items:
            type: string
        category:
          type: string
      example:
        appId: "appId"
        appName: "appName"
        appSources: ["source1", "source2"]
        category: "category"

    googlerpcStatus:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/protobufAny'

    protobufAny:
      type: object
      properties:
        "@type":
          type: string