openapi: 3.0.0
info:
  title: title
  version: "1.0.0"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /auth/login:
    post:
      $ref: "./endpoints/auth.yaml#/login"
