/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Get Apps API
 * OpenAPI spec version: 1.0
 */
export interface V1GetAppsRequest {
  /** Filter by application name */
  appName?: string;
  /** Filter by category */
  category?: string;
  pageNumber?: number;
  pageSize?: number;
}

export interface V1GetAppsResponse {
  appRows?: V1AppRow[];
  totalCount?: number;
}

export interface V1AppRow {
  appId?: string;
  appName?: string;
  appSources?: string[];
  category?: string;
}

export interface GooglerpcStatus {
  code?: number;
  message?: string;
  details?: ProtobufAny[];
}

export interface ProtobufAny {
  '@type'?: string;
}

